### ISSUE TITLE
管理员登录后，右上角的头像无法显示

### ISSUE THREAD

**Issue by leiddev** [xpleaf/Blog_mini#30]
管理员登录后，右上角的头像无法显示，也没见可以设置头像的地方

**Comment by xpleaf** [comment]
头像是通过用户的邮箱使用gravatar生成的，不过目前来看，需要翻墙才可以使用该服务。

**Comment by lushenle** [comment]
好像能翻墙了，还是一样的不能获得头像，可以看看是否可以改进一下吗？

**Comment by lushenle** [comment]
http://gravatar.duoshuo.com/avatar/36c0d699c789a19cb38c7098fb902a5e?s=40&d=identicon&r=g

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by imlonghao** [comment]
看起来多说的 gravatar 反代已经放弃，域名已无法解析

目前已经切换所使用的反代地址，请重新 `git pull` 再试
