### ISSUE TITLE
刚学习了Python16天，想试试你的博客系统，发生如下错误 ！！！

### ISSUE THREAD

**Issue by jacknesstjh** [xpleaf/Blog_mini#31]
jackness@ubuntu:~/project/Blog_mini$ virtualenv venv
New python executable in /home/jackness/project/Blog_mini/venv/bin/python
Installing setuptools, pip, wheel...done.
jackness@ubuntu:~/project/Blog_mini$ ls
app        LICENSE    migrations  README.md     requirements.txt
config.py  manage.py  Procfile    requirements  venv
jackness@ubuntu:~/project/Blog_mini$ source venv/bin/activate
(venv) jackness@ubuntu:~/project/Blog_mini$ pip install -i http://pypi.douban.com/simple/ -r requirements/common.txt
Looking in indexes: http://pypi.douban.com/simple/
Collecting Flask==0.10.1 (from -r requirements/common.txt (line 1))
  The repository located at pypi.douban.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.douban.com'.
  Could not find a version that satisfies the requirement Flask==0.10.1 (from -r requirements/common.txt (line 1)) (from versions: )
No matching distribution found for Flask==0.10.1 (from -r requirements/common.txt (line 1))
The repository located at pypi.douban.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.douban.com'.
错误发生在我安装Blog mini需求文件的时候，这个是什么原因呢？希望大神帮我看下，我是个才学了16天Python的小菜鸟，只是想学习下你的博客系统运用下。谢谢大神！！！

**Comment by imlonghao** [comment]
代码块请放置在 ``` 中

> The repository located at pypi.douban.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.douban.com'.

请使用 `pip install -i https://pypi.douban.com/simple/ -r requirements/common.txt`

**Comment by jacknesstjh** [comment]
是我Ubuntu的问题,重写之后好了.

**Comment by xpleaf** [comment]
OK
