### ISSUE TITLE
关于ssl证书的问题

### ISSUE THREAD

**Issue by ycneverGU** [xpleaf/Blog_mini#37]
部署完给网站加ssl证书，在chrome上会提示‘’您与此网站建立的连接并非完全安全‘’
希望作者能解决一下这个问题
http://www.ip110.com/faq/technique/978.shtml

**Comment by imlonghao** [comment]
可否通过浏览器的控制台（F12）里面的 Console， 然后把跨域的资源链接贴出来以便于修改？

**Comment by ycneverGU** [comment]
![image](https://user-images.githubusercontent.com/31086443/44991993-884f0480-afc8-11e8-8837-7a38f961a29c.png)

**Comment by imlonghao** [comment]
在 8aaa58b 的时候我已经改过一次，但是似乎没改全，这次应该就全部将 gravatar 服务换走了
