### ISSUE TITLE
项目后续维护计划？

### ISSUE THREAD

**Issue by tpoisonooo** [xpleaf/Blog_mini#47]
挺好的项目，推测作者最近忙于工作/学业无法维护。
最近简书嗝屁，我在找一个合适的博客系统部署到自己服务器。
你要是不嫌麻烦，我就顺手给你维护好了。

**Comment by 1344098010** [comment]
大哥你维护的时候能不能把代码提到python3.6以上，学生我最近在照猫画虎，但是出现了种种问题，希望老大哥们能做一个实例，以供我等参考。

**Comment by 1344098010** [comment]
大哥你维护的时候能不能把代码提到python3.6以上，让我们参考一下。本人最近在照葫芦画瓢但是能力有限，遇到很多问题解决起来很吃力。

**Comment by xpleaf** [comment]
@tpoisonooo 确实是忙于工作没有时间是整理，去年有段时间在做重构的，可惜进行了一点就被其他事情忙着了。我后续再看一下，非常感谢，保持联系！

**Comment by xpleaf** [comment]
@1344098010 这确实是个问题，之前也有不少人提到过这个问题，这个只能等到后续有时间重构再来搞。不过你可以看看Flask Web这本书，已经出了Python 3.x版本的，虽然是英文版，不过相对比较浅显，可以先参考一下那个。

**Comment by tpoisonooo** [comment]
裁员大潮，看来都在忙~
