### ISSUE TITLE
Double requirement given: gunicorn

### ISSUE THREAD

**Issue by yarving** [xpleaf/Blog_mini#6]
运行`pip install -r requirements.txt`时报错：
```
Double requirement given: gunicorn==19.4.5 (from -r requirements.txt (line 2)) (already in gunicorn==19.4.5 (from -r requirements/common.txt (line 17)), name='gunicorn')
```
查看了下是requirements.txt和requirements/common.txt都定义了gunicorn

**Comment by xpleaf** [comment]
直接使用：pip install -r requirements/common.txt就可以了

**Comment by xpleaf** [comment]
直接使用：pip install -r requirements/common.txt就可以了

**Comment by xpleaf** [comment]
直接使用：pip install -r requirements/common.txt就可以了
