### ISSUE TITLE
求问插入图片功能

### ISSUE THREAD

**Issue by Zhiwei1996** [xpleaf/Blog_mini#8]
作者你好，我用的你写的程序搭建的博客
我想请问下博文中插入图片的操作情况
好像是要贴上图片的链接地址，是要把图片上传到服务器然后写图片路径来实现图片插入嘛
还算有其它方法只是我还没解锁，不会用

**Comment by xpleaf** [comment]
你好。目前图片上传功能还没有做。你可以把项目Fork到你的仓库后自己做，可参考思路：图片保存在服务器固定的目录中，用数据库保存图片的信息（与博客文章的关联信息以及图片在服务器中的路径信息等）。

**Comment by Zhiwei1996** [comment]
好的，多谢
我尽力，目前还是刚开始学Flask，水平很菜
有不懂的到时候再请教你，有空还望指点

--
Sent using Mail.Ru

Sunday, 28 August 2016, 10:25PM +08:00 from xpleaf notifications@github.com<mailto:notifications@github.com>:


你好。目前图片上传功能还没有做。你可以把项目Fork到你的仓库后自己做，可参考思路：图片保存在服务器固定的目录中，用数据库保存图片的信息（与博客文章的关联信息以及图片在服务器中的路径信息等）。

**Comment by xpleaf** [comment]
不客气的，加油！
